[build]
builder = "dockerfile"

[deploy]
startCommand = "poetry run gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 run:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production" 