"""Add description and created_at to Permission model

Revision ID: 15aab2d9106a
Revises: aa41d200f883
Create Date: 2025-06-28 15:05:38.610718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15aab2d9106a'
down_revision = 'aa41d200f883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('permission', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'created_at')
    op.drop_column('permission', 'description')
    # ### end Alembic commands ###
