"""empty message

Revision ID: 47d3bc3aa276
Revises: 15aab2d9106a
Create Date: 2025-06-29 11:35:53.415191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d3bc3aa276'
down_revision = '15aab2d9106a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
