"""corrige FK user-permission

Revision ID: 9191e81bbf5a
Revises: fd6793971883
Create Date: 2025-06-21 00:46:34.861546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9191e81bbf5a'
down_revision: Union[str, Sequence[str], None] = 'fd6793971883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permission', sa.Column('permission_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'user_permission', type_='foreignkey')
    op.create_foreign_key(None, 'user_permission', 'permission', ['permission_id'], ['id'])
    op.drop_column('user_permission', 'family_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permission', sa.Column('family_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'user_permission', type_='foreignkey')
    op.create_foreign_key(None, 'user_permission', 'family', ['family_id'], ['id'])
    op.drop_column('user_permission', 'permission_id')
    # ### end Alembic commands ###
