"""Add transactions table

Revision ID: c21133b4aace
Revises: 3353aec3766e
Create Date: 2025-08-02 15:34:31.304682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21133b4aace'
down_revision = '3353aec3766e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
